name = "shrill-snowflake-4713"
main = "worker.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ilp-db"
database_id = "61674b99-ac1e-4892-a857-b527d7ea7b30"

